apiVersion: v1
kind: Service
metadata:
  name: devops-django-service
  namespace: NAMESPACE_PLACEHOLDER
spec:
  type: NodePort
  selector:
    app: devops-django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
